### PR TITLE
Closes #5. Changed Copyright Party.

### LINKED ISSUE #5: LICENSE
As far as I am aware, it is not possible for a non-entity "ipfs-shipyard" to hold a copyright. To be legally binding, the LICENSE should be attributed to "Protocol Labs and Associated Developers".

### PR DESCRIPTION
**Pull request by nothingismagick**
Simple change to make Protocol Labs the copyright holder.

### CODE REVIEW

**Comment by hacdias** [comment]
Thanks @nothingismagick!

**Comment by nothingismagick** [comment]
np

**Comment by nothingismagick** [comment]
@hacdias - On a hunch, I looked into other LICENSE files in other protocol repos - and it seems that this issue is rather prolific. Some older ones are in @jbenet 's name, others are "IPFS", which is at best a trademark and not a legal entity. I am not a lawyer, but it might be worthwhile to have someone with rights to every repo do a cleanup. Open source license compliance is really about dotting all the **i**'s and crossing the **t**'s.

**Comment by hacdias** [comment]
Thanks for noticing that. I just opened a bunch of PRs to add most of them on Shipyard. I'll take a look at IPFS org to see which ones are left and submit a PR.

**Pull request merged**
